// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpsiyqwjczktqckzulfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwc2l5cXdqY3prdHFja3p1bGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTQxMzcsImV4cCI6MjA2NDA5MDEzN30.w6UKxY-QHD6SiQIFPtGSKke4ZI0Kg1W8HEHCzaCy1Ic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);